import {
  Metadata,
  MetadataCreator,
  MetadataName,
  MetadataDescription,
  MintButton,
  MintQuantity,
  SalesInfo,
  CollectionAddress,
  MaxQuantity,
  Inventory,
  TotalPrice,
  SalesTiming,
  SaleActiveAlert,
  SaleEndedAlert,
  Thumbnail,
  VideoRenderer,
  AudioRenderer,
  TxStatus,
} from './components/drop-components'

export const DropsComponents = {
  Metadata,
  MetadataCreator,
  MetadataName,
  MetadataDescription,
  MintButton,
  MintQuantity,
  SalesInfo,
  CollectionAddress,
  MaxQuantity,
  Inventory,
  TotalPrice,
  SalesTiming,
  SaleActiveAlert,
  SaleEndedAlert,
  Thumbnail,
  VideoRenderer,
  AudioRenderer,
  TxStatus,
}

export { DropsMinter } from './components/DropsMinter'
